// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { devLocalAuth } from "@/lib/localAuth";

const LOCAL_AUTH = devLocalAuth() !== null;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/**
 * Configuration manquante : on n'échoue PAS à l'import (page blanche). main.tsx
 * affiche un écran d'erreur explicite à la place de l'application.
 */
export const supabaseConfigError: string | null =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? "Variables d'environnement manquantes : VITE_SUPABASE_URL et/ou VITE_SUPABASE_PUBLISHABLE_KEY. Renseignez-les dans le fichier .env puis redémarrez le serveur (ou relancez le build)."
    : null;

// Stockage résilient : si localStorage est indisponible (mode privé, cookies/site
// data bloqués, extension de confidentialité...), on bascule sur un stockage mémoire
// pour que l'authentification ne casse pas silencieusement.
const memoryStore = new Map<string, string>();
const memoryStorage = {
  getItem: (key: string) => (memoryStore.has(key) ? memoryStore.get(key)! : null),
  setItem: (key: string, value: string) => {
    memoryStore.set(key, value);
  },
  removeItem: (key: string) => {
    memoryStore.delete(key);
  },
};

const getSafeStorage = () => {
  try {
    const testKey = "__supabase_storage_test__";
    window.localStorage.setItem(testKey, "1");
    window.localStorage.removeItem(testKey);
    return window.localStorage;
  } catch {
    console.warn(
      "[Supabase] localStorage indisponible — bascule sur un stockage mémoire (session non persistée)."
    );
    return memoryStorage;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Valeurs factices si la config manque : le client est créé mais jamais utilisé
// (l'application n'est pas montée, voir main.tsx).
export const supabase = createClient<Database>(
  SUPABASE_URL || "http://localhost:54321",
  SUPABASE_PUBLISHABLE_KEY || "missing-key",
  {
    // V3 : en connexion locale (sans Supabase), aucune session persistée ni rafraîchie — sinon une
    // ancienne session fait attendre le verrou d'authentification (« LockManager … timed out »).
    auth: LOCAL_AUTH
      ? { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false }
      : {
          storage: getSafeStorage(),
          persistSession: true,
          autoRefreshToken: true,
        },
  },
);
